name: Run All Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      test-dirs: ${{ steps.find-tests.outputs.test-dirs }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Find test.sh files
      id: find-tests
      run: |
        # Find all test.sh files and get their directories
        test_dirs=$(find . -name "test.sh" -type f | xargs dirname | sort | uniq | jq -R -s -c 'split("\n")[:-1]')
        echo "test-dirs=$test_dirs" >> $GITHUB_OUTPUT
        echo "Found test directories: $test_dirs"

  test:
    runs-on: ubuntu-latest
    needs: discover
    if: needs.discover.outputs.test-dirs != '[]'
    strategy:
      matrix:
        test-dir: ${{ fromJson(needs.discover.outputs.test-dirs) }}
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run tests in ${{ matrix.test-dir }}
      working-directory: ${{ matrix.test-dir }}
      run: ./test.sh
